#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.3.3 effective-5.10 (swiftlang-6.3.3.1.3 clang-2100.1.1.101)
#ifndef LOCALSDKCORE_SWIFT_H
#define LOCALSDKCORE_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif // defined(__OBJC__)
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  if __has_feature(generalized_swift_name)
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  else
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
#  endif
# else
#  define SWIFT_ENUM(_type, _name, _extensibility) _type _name; enum 
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM_TAG)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_TAG enum
# else
#  define SWIFT_ENUM_TAG
# endif
#endif
#if !defined(SWIFT_ENUM_FWD_DECL)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_FWD_DECL(_type, _name) enum _name : _type;
# else
#  define SWIFT_ENUM_FWD_DECL(_type, _name) typedef _type _name;
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_AVAILABILITY_DOMAIN)
# define SWIFT_AVAILABILITY_DOMAIN(dom, ...) __attribute__((availability(domain: dom, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if !__has_feature(nullability)
# define _Nonnull
# define _Nullable
# define _Null_unspecified
#elif !defined(__OBJC__)
# pragma clang diagnostic ignored "-Wnullability-extension"
#endif
#if !__has_feature(nullability_nullable_result)
# define _Nullable_result _Nullable
#endif
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="LocalSDKCore",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(__cplusplus)
} // extern "C"
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#endif // defined(__OBJC__)
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="LocalSDKCore",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSString;
/// Configuration, for Objective-C callers.
/// A class rather than the Swift <code>struct</code>, and mutable rather than built by
/// chained <code>with…</code> calls: <code>Config</code>’s builder methods return a value, which is not
/// a shape Objective-C can use.
SWIFT_CLASS_NAMED("LSDKConfig")
@interface LSDKConfig : NSObject
/// <code>"PRECISE"</code>, <code>"STANDARD"</code> or <code>"EFFICIENT"</code>. An unrecognised value leaves
/// the mode unchanged rather than failing — see <code>config</code>.
@property (nonatomic, copy) NSString * _Nonnull trackingMode;
@property (nonatomic) BOOL allowMockLocation;
@property (nonatomic) double horizontalAccuracyThreshold;
@property (nonatomic) BOOL backgroundLocationEnabled;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@protocol LSDKLocationDelegate;
/// The SDK, for Objective-C callers.
/// <code>LocalSDK</code> is a Swift <code>enum</code>, which is invisible to Objective-C, so this is a
/// class facade over it. It adds no behaviour — every method forwards.
/// Everything an Objective-C caller can act on is here. The omissions are omitted
/// because they cannot be represented, not because they were forgotten:
/// <ul>
///   <li>
///     <code>locations()</code> and <code>errors()</code> return <code>AsyncStream</code>, which has no
///     Objective-C form. Use <code>setLocationDelegate:</code>, which carries the same values.
///   </li>
///   <li>
///     <code>onLocation:</code>/<code>onError:</code> are closure registration, which the delegate
///     already covers.
///   </li>
/// </ul>
/// <code>PermissionStatus</code> cannot cross either — it carries associated values — but the
/// information in it can, so it is flattened rather than dropped: <code>locationPermissionStatus</code>
/// gives the case as a string and <code>hasPreciseLocation</code> the accuracy flag.
SWIFT_CLASS_NAMED("LSDKLocalSDK")
@interface LSDKLocalSDK : NSObject
/// Not instantiable — every member is a class method, mirroring the Swift
/// enum’s static shape.
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
+ (void)initializeWithApiKey:(NSString * _Nonnull)apiKey;
+ (void)setConfig:(LSDKConfig * _Nonnull)config;
+ (void)startTracking;
+ (void)stopTracking;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL isTracking;)
+ (BOOL)isTracking SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)checkLocationPermission SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)checkBackgroundLocationPermission SWIFT_WARN_UNUSED_RESULT;
/// The current permission state, as one of <code>"notDetermined"</code>, <code>"denied"</code>,
/// <code>"restricted"</code>, <code>"whenInUse"</code> or <code>"always"</code>.
/// The two <code>check…</code> methods above answer “can I track?”; this answers “why
/// not, and what should I show the user?” — which are different questions.
/// A <code>BOOL</code> collapses <em>not asked yet</em>, <em>declined</em>, and <em>blocked by policy</em>
/// into one value, and those need three different responses: show the primer,
/// deep-link to Settings, or explain that the choice is not the user’s to make.
/// Swift callers have <code>LocalSDK.locationPermissionStatus()</code>, which returns the
/// enum with its associated values. This exists because that enum cannot cross
/// into Objective-C — and through it, into React Native and similar hosts,
/// which is where branching on the distinction is most common.
/// <code>@MainActor</code>, matching the Swift method it forwards to. Objective-C does not
/// enforce that, so a bridged host calling from a background queue — React
/// Native’s bridge queue, for instance — must hop to main first.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull locationPermissionStatus;)
+ (NSString * _Nonnull)locationPermissionStatus SWIFT_WARN_UNUSED_RESULT;
/// Whether full-accuracy location is available.
/// <code>false</code> when the user chose Approximate Location (iOS 14+), and also when
/// nothing has been granted — so read it together with <code>locationPermissionStatus</code>
/// rather than on its own. Reported separately because precision is
/// independent of the authorization level: “whenInUse” can be either.
/// <code>@MainActor</code>, for the same reason as <code>locationPermissionStatus</code>.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL hasPreciseLocation;)
+ (BOOL)hasPreciseLocation SWIFT_WARN_UNUSED_RESULT;
/// <code>@MainActor</code>, matching the Swift API: this presents a system prompt, so
/// Objective-C callers must invoke it on the main thread. That was already the
/// requirement; the annotation makes it enforced rather than assumed.
+ (void)requestLocationPermissionWithCompletion:(void (^ _Nullable)(BOOL))completion;
+ (void)requestBackgroundLocationPermissionWithCompletion:(void (^ _Nullable)(BOOL))completion;
+ (NSString * _Nonnull)deviceIdentifier SWIFT_WARN_UNUSED_RESULT;
+ (void)setUserIdentifier:(NSString * _Nonnull)userId;
/// Key-value pairs attached to every subsequent location.
/// <code>[String: String]</code> bridges to <code>NSDictionary</code> without loss, so this is here
/// rather than in the not-bridgeable list — attaching caller context is too
/// common a need to leave Swift-only.
+ (void)setMetadata:(NSDictionary<NSString *, NSString *> * _Nonnull)metadata;
+ (BOOL)isBackgroundRefreshEnabled SWIFT_WARN_UNUSED_RESULT;
+ (void)reset;
/// Set the receiver for locations and errors. Pass <code>nil</code> to clear.
/// The Objective-C delegate is retained by an adapter held here, because the
/// SDK’s Swift delegate is <code>weak</code> and the adapter would otherwise be
/// deallocated the moment this method returned. The caller’s own object is
/// still held weakly by that adapter, so setting a delegate does not create a
/// retain cycle with the caller.
+ (void)setLocationDelegate:(id <LSDKLocationDelegate> _Nullable)delegate;
@end

@class NSNumber;
/// A location, for Objective-C callers.
/// <code>Location</code> is a Swift <code>struct</code>, which does not cross the bridge at all, so
/// this is a reference-type view of the same values rather than a second model.
/// Conversion happens once, when the SDK hands a location out.
/// Optionals that are value types in Swift — <code>metadata</code>, <code>arrivalDate</code>,
/// <code>departureDate</code> — surface as nullable object types here, because <code>Int64?</code>
/// cannot be represented in Objective-C. <code>arrivalDate</code> and <code>departureDate</code> are
/// <code>NSNumber?</code> for that reason, and are non-nil only on visit rows.
SWIFT_CLASS_NAMED("LSDKLocation")
@interface LSDKLocation : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull identifier;
/// Epoch milliseconds, UTC. The instant the position was fixed, not the
/// instant the SDK processed it.
@property (nonatomic, readonly) int64_t timestamp;
@property (nonatomic, readonly) BOOL isMock;
@property (nonatomic, readonly) double speed;
@property (nonatomic, readonly) double horizontalAccuracy;
@property (nonatomic, readonly) double verticalAccuracy;
@property (nonatomic, readonly) double altitude;
@property (nonatomic, readonly) double bearing;
@property (nonatomic, readonly) double latitude;
@property (nonatomic, readonly) double longitude;
/// <code>"MOVING"</code>, <code>"STATIONARY"</code> or <code>"VISIT"</code> — the raw value, so it matches
/// what appears in the exported data.
@property (nonatomic, readonly, copy) NSString * _Nonnull type;
@property (nonatomic, readonly) NSInteger batteryLevel;
@property (nonatomic, readonly, copy) NSString * _Nonnull batteryStatus;
@property (nonatomic, readonly, copy) NSString * _Nonnull deviceIdentifier;
@property (nonatomic, readonly, copy) NSString * _Nonnull userIdentifier;
/// UTC offset in force at <code>timestamp</code>, as <code>±HH:MM</code>.
@property (nonatomic, readonly, copy) NSString * _Nonnull timezoneOffset;
@property (nonatomic, readonly) BOOL networkStatus;
@property (nonatomic, readonly, copy) NSString * _Nonnull trackingMode;
@property (nonatomic, readonly) BOOL locationPermission;
@property (nonatomic, readonly, copy) NSString * _Nonnull brand;
@property (nonatomic, readonly, copy) NSString * _Nonnull model;
@property (nonatomic, readonly, copy) NSString * _Nonnull os;
@property (nonatomic, readonly, copy) NSString * _Nonnull osVersion;
@property (nonatomic, readonly, copy) NSString * _Nonnull sdkVersion;
@property (nonatomic, readonly, copy) NSString * _Nonnull appVersionName;
@property (nonatomic, readonly, copy) NSString * _Nonnull appVersionCode;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, NSString *> * _Nullable metadata;
/// When the stay began. Non-nil only on a visit; <code>nil</code> when the platform
/// could not determine it.
@property (nonatomic, readonly, strong) NSNumber * _Nullable arrivalDate;
/// When the stay ended. Non-nil only on a visit, and <code>nil</code> while it is still
/// in progress.
@property (nonatomic, readonly, strong) NSNumber * _Nullable departureDate;
/// This location as a dictionary of plain foundation types.
/// For hosts that cannot see Objective-C properties, only serialisable
/// values — React Native’s bridge marshals <code>NSString</code>, <code>NSNumber</code>, <code>BOOL</code>,
/// <code>NSDictionary</code> and <code>NSArray</code> and nothing else, so a <code>LSDKLocation</code> reaches
/// JavaScript as an opaque handle unless it is flattened first.
/// Key names match the columns of an exported CSV, so a row observed in
/// JavaScript lines up with the same row on disk. <code>arrival_date</code>,
/// <code>departure_date</code> and <code>metadata</code> are absent rather than null when they do
/// not apply — only visit rows carry the dates.
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nonnull asDictionary;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Receives locations, for Objective-C callers.
/// Class-bound and <code>@objc</code>, so it can be adopted by an Objective-C class. Held
/// weakly by the SDK, as the Swift delegate is.
SWIFT_PROTOCOL_NAMED("LSDKLocationDelegate")
@protocol LSDKLocationDelegate
- (void)locationDidUpdate:(LSDKLocation * _Nonnull)location;
- (void)locationDidFail:(NSString * _Nonnull)error;
@end

#endif // defined(__OBJC__)
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 6.3.3 effective-5.10 (swiftlang-6.3.3.1.3 clang-2100.1.1.101)
#ifndef LOCALSDKCORE_SWIFT_H
#define LOCALSDKCORE_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif // defined(__OBJC__)
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  if __has_feature(generalized_swift_name)
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  else
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
#  endif
# else
#  define SWIFT_ENUM(_type, _name, _extensibility) _type _name; enum 
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM_TAG)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_TAG enum
# else
#  define SWIFT_ENUM_TAG
# endif
#endif
#if !defined(SWIFT_ENUM_FWD_DECL)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_FWD_DECL(_type, _name) enum _name : _type;
# else
#  define SWIFT_ENUM_FWD_DECL(_type, _name) typedef _type _name;
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_AVAILABILITY_DOMAIN)
# define SWIFT_AVAILABILITY_DOMAIN(dom, ...) __attribute__((availability(domain: dom, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if !__has_feature(nullability)
# define _Nonnull
# define _Nullable
# define _Null_unspecified
#elif !defined(__OBJC__)
# pragma clang diagnostic ignored "-Wnullability-extension"
#endif
#if !__has_feature(nullability_nullable_result)
# define _Nullable_result _Nullable
#endif
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="LocalSDKCore",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(__cplusplus)
} // extern "C"
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#endif // defined(__OBJC__)
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="LocalSDKCore",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSString;
/// Configuration, for Objective-C callers.
/// A class rather than the Swift <code>struct</code>, and mutable rather than built by
/// chained <code>with…</code> calls: <code>Config</code>’s builder methods return a value, which is not
/// a shape Objective-C can use.
SWIFT_CLASS_NAMED("LSDKConfig")
@interface LSDKConfig : NSObject
/// <code>"PRECISE"</code>, <code>"STANDARD"</code> or <code>"EFFICIENT"</code>. An unrecognised value leaves
/// the mode unchanged rather than failing — see <code>config</code>.
@property (nonatomic, copy) NSString * _Nonnull trackingMode;
@property (nonatomic) BOOL allowMockLocation;
@property (nonatomic) double horizontalAccuracyThreshold;
@property (nonatomic) BOOL backgroundLocationEnabled;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@protocol LSDKLocationDelegate;
/// The SDK, for Objective-C callers.
/// <code>LocalSDK</code> is a Swift <code>enum</code>, which is invisible to Objective-C, so this is a
/// class facade over it. It adds no behaviour — every method forwards.
/// Everything an Objective-C caller can act on is here. The omissions are omitted
/// because they cannot be represented, not because they were forgotten:
/// <ul>
///   <li>
///     <code>locations()</code> and <code>errors()</code> return <code>AsyncStream</code>, which has no
///     Objective-C form. Use <code>setLocationDelegate:</code>, which carries the same values.
///   </li>
///   <li>
///     <code>onLocation:</code>/<code>onError:</code> are closure registration, which the delegate
///     already covers.
///   </li>
/// </ul>
/// <code>PermissionStatus</code> cannot cross either — it carries associated values — but the
/// information in it can, so it is flattened rather than dropped: <code>locationPermissionStatus</code>
/// gives the case as a string and <code>hasPreciseLocation</code> the accuracy flag.
SWIFT_CLASS_NAMED("LSDKLocalSDK")
@interface LSDKLocalSDK : NSObject
/// Not instantiable — every member is a class method, mirroring the Swift
/// enum’s static shape.
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
+ (void)initializeWithApiKey:(NSString * _Nonnull)apiKey;
+ (void)setConfig:(LSDKConfig * _Nonnull)config;
+ (void)startTracking;
+ (void)stopTracking;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL isTracking;)
+ (BOOL)isTracking SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)checkLocationPermission SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)checkBackgroundLocationPermission SWIFT_WARN_UNUSED_RESULT;
/// The current permission state, as one of <code>"notDetermined"</code>, <code>"denied"</code>,
/// <code>"restricted"</code>, <code>"whenInUse"</code> or <code>"always"</code>.
/// The two <code>check…</code> methods above answer “can I track?”; this answers “why
/// not, and what should I show the user?” — which are different questions.
/// A <code>BOOL</code> collapses <em>not asked yet</em>, <em>declined</em>, and <em>blocked by policy</em>
/// into one value, and those need three different responses: show the primer,
/// deep-link to Settings, or explain that the choice is not the user’s to make.
/// Swift callers have <code>LocalSDK.locationPermissionStatus()</code>, which returns the
/// enum with its associated values. This exists because that enum cannot cross
/// into Objective-C — and through it, into React Native and similar hosts,
/// which is where branching on the distinction is most common.
/// <code>@MainActor</code>, matching the Swift method it forwards to. Objective-C does not
/// enforce that, so a bridged host calling from a background queue — React
/// Native’s bridge queue, for instance — must hop to main first.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull locationPermissionStatus;)
+ (NSString * _Nonnull)locationPermissionStatus SWIFT_WARN_UNUSED_RESULT;
/// Whether full-accuracy location is available.
/// <code>false</code> when the user chose Approximate Location (iOS 14+), and also when
/// nothing has been granted — so read it together with <code>locationPermissionStatus</code>
/// rather than on its own. Reported separately because precision is
/// independent of the authorization level: “whenInUse” can be either.
/// <code>@MainActor</code>, for the same reason as <code>locationPermissionStatus</code>.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL hasPreciseLocation;)
+ (BOOL)hasPreciseLocation SWIFT_WARN_UNUSED_RESULT;
/// <code>@MainActor</code>, matching the Swift API: this presents a system prompt, so
/// Objective-C callers must invoke it on the main thread. That was already the
/// requirement; the annotation makes it enforced rather than assumed.
+ (void)requestLocationPermissionWithCompletion:(void (^ _Nullable)(BOOL))completion;
+ (void)requestBackgroundLocationPermissionWithCompletion:(void (^ _Nullable)(BOOL))completion;
+ (NSString * _Nonnull)deviceIdentifier SWIFT_WARN_UNUSED_RESULT;
+ (void)setUserIdentifier:(NSString * _Nonnull)userId;
/// Key-value pairs attached to every subsequent location.
/// <code>[String: String]</code> bridges to <code>NSDictionary</code> without loss, so this is here
/// rather than in the not-bridgeable list — attaching caller context is too
/// common a need to leave Swift-only.
+ (void)setMetadata:(NSDictionary<NSString *, NSString *> * _Nonnull)metadata;
+ (BOOL)isBackgroundRefreshEnabled SWIFT_WARN_UNUSED_RESULT;
+ (void)reset;
/// Set the receiver for locations and errors. Pass <code>nil</code> to clear.
/// The Objective-C delegate is retained by an adapter held here, because the
/// SDK’s Swift delegate is <code>weak</code> and the adapter would otherwise be
/// deallocated the moment this method returned. The caller’s own object is
/// still held weakly by that adapter, so setting a delegate does not create a
/// retain cycle with the caller.
+ (void)setLocationDelegate:(id <LSDKLocationDelegate> _Nullable)delegate;
@end

@class NSNumber;
/// A location, for Objective-C callers.
/// <code>Location</code> is a Swift <code>struct</code>, which does not cross the bridge at all, so
/// this is a reference-type view of the same values rather than a second model.
/// Conversion happens once, when the SDK hands a location out.
/// Optionals that are value types in Swift — <code>metadata</code>, <code>arrivalDate</code>,
/// <code>departureDate</code> — surface as nullable object types here, because <code>Int64?</code>
/// cannot be represented in Objective-C. <code>arrivalDate</code> and <code>departureDate</code> are
/// <code>NSNumber?</code> for that reason, and are non-nil only on visit rows.
SWIFT_CLASS_NAMED("LSDKLocation")
@interface LSDKLocation : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull identifier;
/// Epoch milliseconds, UTC. The instant the position was fixed, not the
/// instant the SDK processed it.
@property (nonatomic, readonly) int64_t timestamp;
@property (nonatomic, readonly) BOOL isMock;
@property (nonatomic, readonly) double speed;
@property (nonatomic, readonly) double horizontalAccuracy;
@property (nonatomic, readonly) double verticalAccuracy;
@property (nonatomic, readonly) double altitude;
@property (nonatomic, readonly) double bearing;
@property (nonatomic, readonly) double latitude;
@property (nonatomic, readonly) double longitude;
/// <code>"MOVING"</code>, <code>"STATIONARY"</code> or <code>"VISIT"</code> — the raw value, so it matches
/// what appears in the exported data.
@property (nonatomic, readonly, copy) NSString * _Nonnull type;
@property (nonatomic, readonly) NSInteger batteryLevel;
@property (nonatomic, readonly, copy) NSString * _Nonnull batteryStatus;
@property (nonatomic, readonly, copy) NSString * _Nonnull deviceIdentifier;
@property (nonatomic, readonly, copy) NSString * _Nonnull userIdentifier;
/// UTC offset in force at <code>timestamp</code>, as <code>±HH:MM</code>.
@property (nonatomic, readonly, copy) NSString * _Nonnull timezoneOffset;
@property (nonatomic, readonly) BOOL networkStatus;
@property (nonatomic, readonly, copy) NSString * _Nonnull trackingMode;
@property (nonatomic, readonly) BOOL locationPermission;
@property (nonatomic, readonly, copy) NSString * _Nonnull brand;
@property (nonatomic, readonly, copy) NSString * _Nonnull model;
@property (nonatomic, readonly, copy) NSString * _Nonnull os;
@property (nonatomic, readonly, copy) NSString * _Nonnull osVersion;
@property (nonatomic, readonly, copy) NSString * _Nonnull sdkVersion;
@property (nonatomic, readonly, copy) NSString * _Nonnull appVersionName;
@property (nonatomic, readonly, copy) NSString * _Nonnull appVersionCode;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, NSString *> * _Nullable metadata;
/// When the stay began. Non-nil only on a visit; <code>nil</code> when the platform
/// could not determine it.
@property (nonatomic, readonly, strong) NSNumber * _Nullable arrivalDate;
/// When the stay ended. Non-nil only on a visit, and <code>nil</code> while it is still
/// in progress.
@property (nonatomic, readonly, strong) NSNumber * _Nullable departureDate;
/// This location as a dictionary of plain foundation types.
/// For hosts that cannot see Objective-C properties, only serialisable
/// values — React Native’s bridge marshals <code>NSString</code>, <code>NSNumber</code>, <code>BOOL</code>,
/// <code>NSDictionary</code> and <code>NSArray</code> and nothing else, so a <code>LSDKLocation</code> reaches
/// JavaScript as an opaque handle unless it is flattened first.
/// Key names match the columns of an exported CSV, so a row observed in
/// JavaScript lines up with the same row on disk. <code>arrival_date</code>,
/// <code>departure_date</code> and <code>metadata</code> are absent rather than null when they do
/// not apply — only visit rows carry the dates.
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nonnull asDictionary;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Receives locations, for Objective-C callers.
/// Class-bound and <code>@objc</code>, so it can be adopted by an Objective-C class. Held
/// weakly by the SDK, as the Swift delegate is.
SWIFT_PROTOCOL_NAMED("LSDKLocationDelegate")
@protocol LSDKLocationDelegate
- (void)locationDidUpdate:(LSDKLocation * _Nonnull)location;
- (void)locationDidFail:(NSString * _Nonnull)error;
@end

#endif // defined(__OBJC__)
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
